replicaCount: 1
image: 
 repository: chartoon/ruby-rails-prod
 tag: 0.3
 pullPolicy: IfNotPresent
 containerPort: 5000
service:
 name: http
 type: NodePort
 externalPort: 5000
 internalPort: 5000
 nodePort: 30606

app: hello-world
