apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: {{ template "homework1.fullname" . }}
 labels:
  chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  app: {{ .Values.app }}
spec:
 replicas: {{ .Values.replicaCount }}
 template:
  metadata:
   labels:
    #app: {{ template "homework1.fullname" . }}
    app: {{ .Values.app }}
  spec:
   containers:
   - name: {{ .Chart.Name }}
     image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
     imagePullPolicy: {{ .Values.image.pullPolicy }}
     ports:
     - containerPort: {{ .Values.service.internalPort }}
     env:
      - name: POSTGRESQL_HOST
        value: {{ template "postgresql.fullname" . }}
      - name: POSTGRESQL_PASSWORD
        valueFrom:
         secretKeyRef:
          name: {{ template "postgresql.fullname" . }}
          key: POSTGRES_PASSWORD
      - name: RAILS_ENV
        value: "production"
